# Generated by Django 3.1.7 on 2021-02-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductManager',
        ),
    ]
