# Generated by Django 3.1.7 on 2021-03-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.IntegerField()),
                ('mobile_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField(default='about')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
