# Generated by Django 3.1.7 on 2021-03-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersetting',
            name='copy_right',
            field=models.CharField(default='copy right text', max_length=200),
        ),
        migrations.AddField(
            model_name='footersetting',
            name='image_web_site',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='footersetting',
            name='about',
            field=models.TextField(default='about text'),
        ),
    ]
