# Generated by Django 3.1.7 on 2021-03-01 12:10

from django.db import migrations, models
import eshop_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0002_auto_20210301_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersetting',
            name='image_web_site',
            field=models.ImageField(blank=True, null=True, upload_to=eshop_settings.models.upload_image_path),
        ),
    ]
