# Generated by Django 3.1.7 on 2021-02-28 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 14, 8, 7, 375186)),
        ),
    ]
