# Generated by Django 3.1.7 on 2021-03-04 13:40

from django.db import migrations, models
import eshop_sliders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=eshop_sliders.models.upload_image_path)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
